baseURL = "https://paperlib.app/"
languageCode = "en-us"
title = "Paperlib | Manage academic papers decently"
theme = "paperlib-theme"
summaryLength = 10

# Build robots.txt file
enableRobotsTXT = true
# google analytics tracking id
googleAnalytics = "G-MK8FN2RB1C" # your analitics ID

# Multilangues setup
# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

# Site Params
[params]
logo = "images/logo.png"

# Gestion des langues : FR / EN / NL / DE
[[Params.listeLangues]]
code = "en"
codeURL = "en"
[[Params.listeLangues]]
code = "中文"
codeURL = "cn"

# meta data
author = "Geo"
description = "Paperlib | Manage academic papers decently"

[Languages]
############# 1 - Site en ENGLISH
[Languages.en]
weight = 1
languageCode = "en-us"
title = "Paperlib"
dateFormat = "January 2, 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerQuicklinkTitle = "Quicklinks"

# cookies
[params.cookies]
enable = true
expire_days = 2

# Hero Area Section
[Languages.en.params.hero]
heading = "Paperlib, to organise academic papers decently"
description = "An open-source and simple academic paper management tool."
button  = true
imageURL   = "../images/ui.png"
screenshotText = 'Screenshot'

[[Languages.en.params.hero.btn]]
name    = "Download"
url     = "download/"
[[Languages.en.params.hero.btn]]
name    = "Donate"
url     = "#donate"
[[Languages.en.params.hero.btn]]
name    = "Quick Start"
url     = "blog/intro/"


[Languages.en.params.donate]
enable  = true
topTitle= "WE WANT TO THANK YOU"
title   = "Donate."
subtitle= ""
button  = true

[[Languages.en.params.donate.btn]]
name = "Buy me a coffee"
url  = "https://www.buymeacoffee.com/geoffreychen777"
[[Languages.en.params.donate.btn]]
name = "Wechat Pay"
url  = "/images/wechat_pay.png"

[Languages.en.params.sponsors]
enable  = true
topTitle= "WE WANT TO THANK YOU"
title   = "Sponsors."
subtitle= ""

[[Languages.en.params.sponsors.logo]]
url = "/images/sponsors/MacStadium.png"


[Languages.en.params.download]
releaseNote = "https://objectstorage.uk-london-1.oraclecloud.com/n/lrarf8ozesjn/b/bucket-20220130-2329/o/distribution%2Felectron-mac%2Fchangelog_en.html"

[[Languages.en.params.download.btn]]
name = "macOS Intel"
icon = "bi-apple"
url  = "https://paperlib.app/distribution/electron-mac/latest.dmg"
caption  = ""

[[Languages.en.params.download.btn]]
name = "macOS Silicon"
icon = "bi-apple"
url  = "https://paperlib.app/distribution/electron-mac-arm/latest.dmg"
caption  = ""

[[Languages.en.params.download.btn]]
name = "Windows"
icon = "bi-windows"
url  = "https://paperlib.app/distribution/electron-win/latest.exe"
caption  = "* Windows 10 or higher"

[[Languages.en.params.download.btn]]
name = "Chrome Extension"
icon = "bi-browser-chrome"
url  = "https://chrome.google.com/webstore/detail/paperlib/kgnpnfbjckgddlednhoblgfdfohhapng?hl=en-GB"
caption  = ""

[[Languages.en.params.download.btn]]
name = "Firefox Extension"
icon = "bi-browser-firefox"
url  = "https://addons.mozilla.org/en-GB/firefox/addon/paperlib"
caption  = ""

############ 2 - Site cn CHINESE
[Languages.cn]
weight = 2
languageCode = "zh-cn"
title = "Paperlib"
dateFormat = "2 January 2006"
home = "Home"
logo = "images/logo.png"
menufixed = false

footerQuicklinkTitle = "链接"

# Hero Area Section
[Languages.cn.params.hero]
heading = "Paperlib 呸啵哩哺，一个理工科简单好用的论文管理工具"
description = "开源！简单！好用！"
button  = true
imageURL   = "../images/ui.png"
screenshotText = '预览'

[[Languages.cn.params.hero.btn]]
name    = "下载"
url     = "download/"
[[Languages.cn.params.hero.btn]]
name    = "捐赠"
url     = "#donate"
[[Languages.cn.params.hero.btn]]
name    = "使用指南"
url     = "blog/intro/"




[Languages.cn.params.donate]
enable  = true
topTitle= "我们感谢您的"
title   = "捐赠."
subtitle= ""
button  = true
[[Languages.cn.params.donate.btn]]
name = "Buy me a coffee"
url  = "https://www.buymeacoffee.com/geoffreychen777"
[[Languages.cn.params.donate.btn]]
name = "微信"
url  = "/images/wechat_pay.png"

[Languages.cn.params.sponsors]
enable  = true
topTitle= "我们感谢您的"
title   = "赞助."
subtitle= ""
[[Languages.cn.params.sponsors.logo]]
url = "/images/sponsors/MacStadium.png"

[Languages.cn.params.download]
releaseNote = "https://objectstorage.uk-london-1.oraclecloud.com/n/lrarf8ozesjn/b/bucket-20220130-2329/o/distribution%2Felectron-mac%2Fchangelog_cn.html"

[[Languages.cn.params.download.btn]]
name = "macOS Silicon"
icon = "bi-apple"
url  = "https://paperlib.app/distribution/electron-mac-arm/latest.dmg"
caption  = ""

[[Languages.cn.params.download.btn]]
name = "Windows"
icon = "bi-windows"
url  = "https://paperlib.app/distribution/electron-win/latest.exe"
caption  = "* Windows 10 or higher"

[[Languages.cn.params.download.btn]]
name = "Chrome Extension"
icon = "bi-browser-chrome"
url  = "https://chrome.google.com/webstore/detail/paperlib/kgnpnfbjckgddlednhoblgfdfohhapng?hl=en-GB"
caption  = ""

[[Languages.cn.params.download.btn]]
name = "Firefox Extension"
icon = "bi-browser-firefox"
url  = "https://addons.mozilla.org/en-GB/firefox/addon/paperlib"
caption  = ""

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name    = "Download"
url     = "download"
weight  = 1
[[menu.nav]]
name    = "Blog"
url     = "blog"
weight  = 2

# Footer Quick links Menu
[[menu.quicklink]]
name    = "About me"
url     = "https://geoch.top/"
weight  = 1
[[menu.quicklink]]
name    = "Github"
url     = "https://github.com/GeoffreyChen777/paperlib"
weight  = 2


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true