name: Deploy Website

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: ["18.12.0"]

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Setup NodeJS Environment ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install Node Module"
        working-directory: ./en
        run: npm install --force

      - name: "Build"
        working-directory: ./en
        run: npm run build

      - name: "Deploy"
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: '.'
          destination-github-username: 'GeoffreyChen777'
          destination-repository-name: 'paperlib-website'
          user-email: hi@paperlib.app
          target-branch: master