name: Deploy Website

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: ["18.12.0"]

    steps:
      - name: "Checkout Project"
        uses: actions/checkout@v2

      - name: Setup NodeJS Environment ${{ matrix.node-versions }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Install Node Module"
        run: npm install --force

      - name: "Build"
        run: npm run build

      - name: "Deploy"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: GeoffreyChen777/paperlib-website
          force_with_lease: true